# Generated by Django 5.0.7 on 2024-08-23 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='description',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('transit_num', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('capacity', models.CharField(max_length=100)),
                ('Bank_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='Bank.bank')),
            ],
        ),
    ]
